name: module

on:
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch:
  push:
    branches-ignore:
      - main

concurrency: test

env:
  TF_INPUT: false
  TF_IN_AUTOMATION: true
  TF_STATE_BUCKET: "env-tfbackend-oss-backend"
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  MONGODB_ATLAS_PRIVATE_KEY: ${{ secrets.MONGODB_ATLAS_PRIVATE_KEY }}
  MONGODB_ATLAS_PUBLIC_KEY: ${{ secrets.MONGODB_ATLAS_PUBLIC_KEY }}
  MONGODB_ATLAS_ORG: ${{ secrets.MONGODB_ATLAS_ORG }}
  SLACK_URL: ${{ secrets.SLACK_URL }}

jobs:
  module:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v2.0.3 # https://github.com/hashicorp/setup-terraform/releases
        with:
          terraform_version: 1.3.5 # https://github.com/hashicorp/terraform/releases
          terraform_wrapper: false

      - uses: actions/setup-go@v4
        with:
          go-version: 1.19

      - name: Terratest
        if: always()
        working-directory: terraform/test/src
        run: |
          export TF_VAR_git=`echo ${GITHUB_REPOSITORY} | sed -e 's|.*/||'`
          go mod download
          go test -v -timeout 90m